scripts:
  image: demo/jd_scripts
  container_name: jd_scripts0
  restart: always
    #如果需要自定定义定时任务的需要自己写好`my_crontab_list.sh`文件 ，取消下面的注释 ，通过 `volumes`挂载进去。
    # volumes:
    # - ./logs:/scripts/logs
  # - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
  tty: true
  environment:
    # 注意环境变量填写值的时候一律不需要引号（"）下面这些只是事例，根据自己的需求增加删除
    #jd cookies
    - JD_COOKIE=pt_key=AAJf9mwBADB2C8OChNxv_17xeeq94KYLq9nwk__guNEpRNznX0StnOUuknrK079oMfR9XMF-sfY;pt_pin=jd_wPcJDZeiQcAi;
    #微信server酱通
    - PUSH_KEY=""
    #Bark App通知
    - BARK_PUSH=""
    #telegram机器人通知
    - TG_BOT_TOKEN=1308621663:AAHU801BM9wktjKgodWEV95N5I0zQFunnyY
    - TG_USER_ID=1031268099

    #钉钉机器人通知
    - DD_BOT_TOKEN=""
    - DD_BOT_SECRET=""
    #京东种豆得豆
    - PLANT_BEAN_SHARECODES=""
    #京东农场
    - FRUITSHARECODES=""
    #京东萌宠
    - PETSHARECODES=""
    - JOY_FEED_COUNT=""
    #京小超
    - SUPERMARKET_SHARECODES=1000
    #兑换多少数量的京豆（1-20之间，或者1000），0默认兑换不兑换，如需兑换把0改成1-20之间的数字或者1000即可
    - MARKET_COIN_TO_BEANS=""
    #是否开启debug模式打印日志
    - JD_DEBUG=true
